version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=storefront.settings.prod
    image: app
    container_name: django_container
    command: gunicorn storefront.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    image: nginx:latest  # Use a custom image name to avoid conflicts
    depends_on:
      - app
    # Removed 'links' as it's deprecated