# Generated by Django 5.1.1 on 2024-10-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Continent',
                'verbose_name_plural': 'Continents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('sovereignty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('native_name', models.CharField(blank=True, help_text='Name of the language in its native script', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SovereignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ISO name of the country (e.g., United States, United Kingdom)', max_length=100, unique=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('native_names', models.TextField(blank=True, help_text='Native names of the country (e.g., Deutschland, Россия)', null=True)),
                ('alternative_names', models.TextField(blank=True, help_text="Alternative names for the country (e.g., 'USA', 'UK')", null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, help_text='Flag of the country', null=True, upload_to='flags/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='foundation.continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_demonym', models.CharField(blank=True, help_text='Demonym in English', max_length=255, null=True, unique=True)),
                ('alternative_demonyms', models.TextField(blank=True, help_text='Array of alternative demonym forms (e.g., adjectives in other languages)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(help_text='Associated country', on_delete=django.db.models.deletion.CASCADE, related_name='demonyms', to='foundation.country')),
            ],
            options={
                'verbose_name': 'Demonym',
                'verbose_name_plural': 'Demonyms',
                'ordering': ['country', 'main_demonym'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.country')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.entityclassification')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('denominations', models.CharField(blank=True, max_length=255)),
                ('issuance_reason', models.TextField(blank=True)),
                ('historical_context', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='foundation.entity')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_periods', to='foundation.country')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alternative name for the language', max_length=255, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='foundation.language')),
            ],
            options={
                'verbose_name': 'Alternative Name',
                'verbose_name_plural': 'Alternative Names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.language')),
            ],
            options={
                'verbose_name': 'Country Language',
                'verbose_name_plural': 'Country Languages',
                'ordering': ['country'],
                'indexes': [models.Index(fields=['country'], name='foundation__country_3b625d_idx'), models.Index(fields=['language'], name='foundation__languag_79f280_idx'), models.Index(fields=['country', 'language'], name='foundation__country_44727e_idx')],
            },
        ),
    ]
