# Generated by Django 5.1.1 on 2024-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='ISO name of the country (e.g., United States, United Kingdom). A Country represents a sovereign state—an independent nation with defined borders, a permanent population, a government, and the capacity to enter into relations with other states. Countries can span various historical periods, maintaining continuity despite changes in governance, leadership, or political systems.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(help_text='An Entity refers to a subnational division or historical administrative unit within a country. Entities can vary in their degree of autonomy and governance structure. They can be provinces, states, kingdoms, duchies, cities, or other administrative regions.', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.country'),
        ),
    ]
