# Generated by Django 5.1.1 on 2024-12-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_alter_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
