# Generated by Django 5.1.1 on 2024-09-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_alter_alternativename_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='iso_name',
            new_name='name',
        ),
    ]
