# Generated by Django 5.1.1 on 2024-12-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_alter_country_iso2_alter_country_iso3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperiod',
            options={'ordering': ['start_date', 'name'], 'verbose_name': 'Historical Period', 'verbose_name_plural': 'Historical Periods'},
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='country',
            field=models.ForeignKey(help_text='Country associated with this historical period.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_periods', to='foundation.country'),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description providing additional context about the historical period.'),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_date',
            field=models.DateField(blank=True, help_text='The ending date of the historical period (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='name',
            field=models.CharField(help_text='Name of the historical period.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='start_date',
            field=models.DateField(blank=True, help_text='The starting date of the historical period (optional).', null=True),
        ),
    ]
