# Generated by Django 5.1.1 on 2024-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_alter_language_options_rename_iso_name_language_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the numismatic / numismatic period (e.g., Third Reich, Late Soviet Union)', max_length=100, unique=True)),
                ('alternative_names', models.TextField(blank=True, help_text="Alternative names for the period (e.g., 'Nazis', 'USSR')", null=True)),
                ('start_year', models.IntegerField(blank=True, help_text='Year the period started (optional)', null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='Year the period ended (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['name'],
            },
        ),
    ]
