# Generated by Django 5.1.1 on 2024-10-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='Name of the numismatic / historical period (e.g., Third Reich, Late Soviet Union)', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CountryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.country')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.period')),
            ],
            options={
                'verbose_name': 'Country Period',
                'verbose_name_plural': 'Country Periods',
                'unique_together': {('country', 'period')},
            },
        ),
        migrations.AddField(
            model_name='country',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='countries_related', through='foundation.CountryPeriod', to='foundation.period'),
        ),
        migrations.AddField(
            model_name='period',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='periods_related', through='foundation.CountryPeriod', to='foundation.country'),
        ),
    ]
