# Generated by Django 5.1.1 on 2024-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_alter_period_name_countryperiod_country_periods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='name',
            field=models.CharField(help_text='Alternative name for the language', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alternative_names',
            field=models.TextField(blank=True, help_text="Alternative names for the country (e.g., 'USA', 'UK')", null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_name',
            field=models.CharField(help_text='ISO name of the country (e.g., United States, United Kingdom)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='native_names',
            field=models.TextField(blank=True, help_text='Native names of the country (e.g., Deutschland, Россия)', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_state_name',
            field=models.CharField(blank=True, help_text='Official name of the country (e.g., United States of America, United Kingdom of Great Britain and Northern Ireland)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='periods',
            field=models.ManyToManyField(blank=True, help_text='Historical periods associated with the country', related_name='countries_related', through='foundation.CountryPeriod', to='foundation.period'),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, help_text='Name of the language in its native script', max_length=100, null=True, unique=True),
        ),
    ]
