# Generated by Django 5.1.1 on 2024-10-01 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_alter_alternativename_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='countries',
        ),
        migrations.AlterField(
            model_name='country',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='countries_related', through='foundation.CountryPeriod', to='foundation.period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='Name of the historical or numismatic period (e.g., Third Reich, Late Soviet Union)', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CurrencyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the currency period (e.g., Deutsche Mark, Euro)', max_length=100)),
                ('alternative_names', models.TextField(blank=True, help_text='Alternative names for the currency period', null=True)),
                ('start_year', models.IntegerField(help_text='Year the currency period started')),
                ('end_year', models.IntegerField(blank=True, help_text='Year the currency period ended (leave blank if ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_periods', to='foundation.country')),
            ],
            options={
                'verbose_name': 'Currency Period',
                'verbose_name_plural': 'Currency Periods',
                'ordering': ['country', 'start_year'],
            },
        ),
    ]
