# Generated by Django 5.1.1 on 2024-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_period_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='coat_of_arms',
            field=models.ImageField(blank=True, help_text='Coat of arms or emblem of the period', null=True, upload_to='periods/'),
        ),
    ]
