# Generated by Django 5.1.1 on 2024-10-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0016_countrylanguage_foundation__country_3b625d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyperiod',
            options={'ordering': ['start_year'], 'verbose_name': 'Currency Period', 'verbose_name_plural': 'Currency Periods'},
        ),
        migrations.RemoveField(
            model_name='currencyperiod',
            name='alternative_names',
        ),
        migrations.RemoveField(
            model_name='currencyperiod',
            name='period',
        ),
        migrations.AddField(
            model_name='currencyperiod',
            name='type',
            field=models.CharField(default='coin', help_text='Type of currency (e.g., coin, banknote)', max_length=50),
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the administrative unit', max_length=100)),
                ('type', models.CharField(help_text='Type of administrative unit (e.g., state, territory)', max_length=100)),
                ('start_year', models.IntegerField(blank=True, help_text='Year the administrative unit was established', null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='Year the administrative unit was dissolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_units', to='foundation.country')),
            ],
            options={
                'verbose_name': 'Administrative Unit',
                'verbose_name_plural': 'Administrative Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='currencyperiod',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_periods', to='foundation.administrativeunit'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the currency (e.g., Mark, Euro)', max_length=100)),
                ('denomination', models.DecimalField(decimal_places=2, help_text='Denomination of the currency', max_digits=10)),
                ('issue_date', models.DateField(help_text='Date the currency was issued')),
                ('type', models.CharField(help_text='Type of currency (e.g., coin, banknote)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='foundation.currencyperiod')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the historical period', max_length=100, unique=True)),
                ('start_year', models.IntegerField(blank=True, help_text='Year the period started (optional)', null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='Year the period ended (optional)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the period', null=True)),
                ('coat_of_arms', models.ImageField(blank=True, help_text='Coat of arms or emblem of the period', null=True, upload_to='periods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_periods', to='foundation.country')),
            ],
            options={
                'verbose_name': 'Historical Period',
                'verbose_name_plural': 'Historical Periods',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='currencyperiod',
            name='historical_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_periods', to='foundation.historicalperiod'),
        ),
    ]
