# Generated by Django 5.1.1 on 2024-09-30 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_name', models.CharField(max_length=100, unique=True)),
                ('official_state_name', models.CharField(max_length=100, unique=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('native_names', models.TextField(blank=True, null=True)),
                ('alternative_names', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['iso_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['iso_name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='description',
            new_name='alternative_names',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='iso_name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.AddField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.language')),
            ],
            options={
                'verbose_name': 'Country Language',
                'verbose_name_plural': 'Country Languages',
                'ordering': ['country'],
            },
        ),
    ]
