# Generated by Django 5.1.1 on 2024-09-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_alternativename_remove_language_alternative_names_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativename',
            options={'ordering': ['name'], 'verbose_name': 'Alternative Name', 'verbose_name_plural': 'Alternative Names'},
        ),
        migrations.RemoveField(
            model_name='language',
            name='alternative_names',
        ),
        migrations.AddField(
            model_name='alternativename',
            name='language',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='foundation.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
