# Generated by Django 5.1.1 on 2024-10-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_remove_period_countries_alter_country_periods_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyperiod',
            options={'ordering': ['period', 'start_year'], 'verbose_name': 'Currency Period', 'verbose_name_plural': 'Currency Periods'},
        ),
        migrations.RemoveField(
            model_name='currencyperiod',
            name='country',
        ),
        migrations.AddField(
            model_name='currencyperiod',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_periods', to='foundation.period'),
        ),
    ]
