# Generated by Django 5.1.1 on 2024-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_alter_currencyperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the period', null=True),
        ),
    ]
