# Generated by Django 5.1.1 on 2024-10-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_period_coat_of_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(help_text='Normalized form of the demonym in English', max_length=255, unique=True)),
                ('alternative_names', models.TextField(blank=True, help_text='Array of alternative demonym forms (e.g., adjectives in other languages)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(help_text='Associated country', on_delete=django.db.models.deletion.CASCADE, related_name='demonyms', to='foundation.country')),
                ('language', models.ForeignKey(blank=True, help_text='Associated language (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demonyms', to='foundation.language')),
            ],
            options={
                'verbose_name': 'Demonym',
                'verbose_name_plural': 'Demonyms',
                'ordering': ['country', 'normalized_name'],
            },
        ),
    ]
