# Generated by Django 5.1.1 on 2024-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_alter_demonym_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, help_text='Flag of the country', null=True, upload_to='flags/'),
        ),
    ]
