# Generated by Django 5.1.1 on 2024-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0015_country_flag'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countrylanguage',
            index=models.Index(fields=['country'], name='foundation__country_3b625d_idx'),
        ),
        migrations.AddIndex(
            model_name='countrylanguage',
            index=models.Index(fields=['language'], name='foundation__languag_79f280_idx'),
        ),
        migrations.AddIndex(
            model_name='countrylanguage',
            index=models.Index(fields=['country', 'language'], name='foundation__country_44727e_idx'),
        ),
    ]
