# Generated by Django 5.1.1 on 2024-10-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0017_alter_currencyperiod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the administrative unit type (e.g., State, Territory)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Administrative Unit Type',
                'verbose_name_plural': 'Administrative Unit Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='currencyperiod',
            name='type',
            field=models.CharField(choices=[('coin', 'Coin'), ('banknote', 'Banknote'), ('stamp', 'Postage Stamp')], default='coin', help_text='Type of currency (e.g., coin, banknote)', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type of administrative unit (e.g., state, territory)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.administrativeunittype'),
        ),
    ]
