# Generated by Django 5.1.1 on 2024-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0019_continent_country_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativeunit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='administrativeunit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='currencyperiod',
            name='administrative_unit',
        ),
        migrations.AlterUniqueTogether(
            name='countryperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='countryperiod',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countryperiod',
            name='period',
        ),
        migrations.RemoveField(
            model_name='country',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_period',
        ),
        migrations.RemoveField(
            model_name='currencyperiod',
            name='historical_period',
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='country_end_year',
            field=models.IntegerField(blank=True, help_text='Year the country was dissolved', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_start_year',
            field=models.IntegerField(blank=True, help_text='Year the country was established', null=True),
        ),
        migrations.DeleteModel(
            name='AdministrativeUnitType',
        ),
        migrations.DeleteModel(
            name='AdministrativeUnit',
        ),
        migrations.DeleteModel(
            name='CountryPeriod',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CurrencyPeriod',
        ),
        migrations.DeleteModel(
            name='HistoricalPeriod',
        ),
    ]
