# Generated by Django 5.1.1 on 2024-10-03 06:47

import django.db.models.deletion
import foundation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0020_remove_administrativeunit_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.PositiveIntegerField(blank=True, help_text='Year the country group was established', null=True, validators=[foundation.models.validate_year])),
                ('end_date', models.PositiveIntegerField(blank=True, help_text='Year the country group was dissolved', null=True, validators=[foundation.models.validate_year])),
            ],
            options={
                'verbose_name': 'Country Group',
                'verbose_name_plural': 'Country Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Currency Type',
                'verbose_name_plural': 'Currency Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.PositiveIntegerField(blank=True, help_text='Start year of the historical period', null=True, validators=[foundation.models.validate_year])),
                ('end_date', models.PositiveIntegerField(blank=True, help_text='End year of the historical period', null=True, validators=[foundation.models.validate_year])),
            ],
            options={
                'verbose_name': 'Historical Period',
                'verbose_name_plural': 'Historical Periods',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IssuanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Issuance Reason',
                'verbose_name_plural': 'Issuance Reasons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SovereignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sovereign Status',
                'verbose_name_plural': 'Sovereign Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='country_end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the country was dissolved', null=True, validators=[foundation.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_start_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the country was established', null=True, validators=[foundation.models.validate_year]),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.PositiveIntegerField(blank=True, help_text='Year the entity was established', null=True, validators=[foundation.models.validate_year])),
                ('end_date', models.PositiveIntegerField(blank=True, help_text='Year the entity was dissolved', null=True, validators=[foundation.models.validate_year])),
                ('entity_type', models.ForeignKey(help_text='Type of the entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.entitytype')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.PositiveIntegerField(blank=True, help_text='Year the currency was introduced', null=True, validators=[foundation.models.validate_year])),
                ('end_date', models.PositiveIntegerField(blank=True, help_text='Year the currency was discontinued', null=True, validators=[foundation.models.validate_year])),
                ('denominations', models.CharField(blank=True, help_text='Denominations of the currency', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the currency', null=True)),
                ('currency_type', models.ForeignKey(help_text='Type of the currency', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='foundation.currencytype')),
                ('entity', models.ForeignKey(help_text='Associated entity', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='foundation.entity')),
                ('issuance_reason', models.ForeignKey(help_text='Reason for currency issuance', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='foundation.issuancereason')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.PositiveIntegerField(blank=True, help_text='Year the parent entity was established', null=True, validators=[foundation.models.validate_year])),
                ('end_date', models.PositiveIntegerField(blank=True, help_text='Year the parent entity was dissolved', null=True, validators=[foundation.models.validate_year])),
                ('entity_type', models.ForeignKey(help_text='Type of the parent entity', on_delete=django.db.models.deletion.CASCADE, related_name='parent_entities', to='foundation.entitytype')),
            ],
            options={
                'verbose_name': 'Parent Entity',
                'verbose_name_plural': 'Parent Entities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='parent_entity',
            field=models.ForeignKey(help_text='Associated parent entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.parententity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sovereign_status',
            field=models.ForeignKey(help_text='Sovereign status of the entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.sovereignstatus'),
        ),
        migrations.CreateModel(
            name='CountryGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(help_text='Associated country', on_delete=django.db.models.deletion.CASCADE, related_name='country_groups', to='foundation.country')),
                ('country_group', models.ForeignKey(help_text='Associated country group', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='foundation.countrygroup')),
            ],
            options={
                'verbose_name': 'Country Group Member',
                'verbose_name_plural': 'Country Group Members',
                'ordering': ['country_group', 'country'],
                'unique_together': {('country_group', 'country')},
            },
        ),
        migrations.CreateModel(
            name='EntityHistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(help_text='Associated entity', on_delete=django.db.models.deletion.CASCADE, related_name='historical_periods', to='foundation.entity')),
                ('historical_period', models.ForeignKey(help_text='Associated historical period', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foundation.historicalperiod')),
            ],
            options={
                'verbose_name': 'Entity Historical Period',
                'verbose_name_plural': 'Entity Historical Periods',
                'ordering': ['entity', 'historical_period'],
                'unique_together': {('entity', 'historical_period')},
            },
        ),
        migrations.CreateModel(
            name='ParentEntityCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(help_text='Associated country', on_delete=django.db.models.deletion.CASCADE, related_name='parent_entities', to='foundation.country')),
                ('country_group', models.ForeignKey(blank=True, help_text='Associated country group (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_entity_countries', to='foundation.countrygroup')),
                ('parent_entity', models.ForeignKey(help_text='Associated parent entity', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='foundation.parententity')),
            ],
            options={
                'verbose_name': 'Parent Entity Country',
                'verbose_name_plural': 'Parent Entity Countries',
                'ordering': ['parent_entity', 'country'],
                'unique_together': {('parent_entity', 'country')},
            },
        ),
    ]
